buresdv/Cork

- Cork/ContentView.swift
- Cork/Views/Installation/Install Package.swift
- Cork/Views/Installation/Reusables/Search Result Row.swift
- Cork/Views/Packages/Package Details.swift
- Cork/Views/Reusables/GroupBox Headline Group.swift
Fixes the packages count when adding or removing packages
Thanks to: [@myihsan](https://github.com/myihsan) and [@brandonhorst](https://github.com/brandonhorst) for the pointers!
> fix: update the package counts when adding/removing packages

- Cork/Views/Reusables/GroupBox Headline Group.swift
- Cork/Views/Start Page/Start Page.swift
Add icons to each item on the start screen, and slightly increase padding to let each item 'breathe' a bit.
> + Start screen icons

- Cork/CorkApp.swift
- Cork/Views/Loading View.swift
- Cork/Views/Maintenance/Maintenance View.swift
- Cork/Views/Maintenance/Sub-Views/Ready View.swift
- Cork/Views/Packages/Package Details/Package Details.swift
- Cork/Views/Settings/Panes/Brew Pane.swift
- Cork/Views/Settings/Panes/General Pane.swift
- Cork/Views/Settings/Panes/Maintenance Pane.swift
- Cork/Views/Settings/Settings View.swift
- Cork/Views/Sidebar/Sidebar View.swift
- Cork/Views/Start Page/Start Page.swift
Fully expecting some/all of these changes to be rejected but I thought I'd have a go at some copy changes to improve consistency/clarity, and reduce some repeated redundant wording 😅  I've left comments explaining my rationale
_Click through to view full-size:_
**Main Window**
| Start | Formula (or Cask) | Maintenance |
| -- | -- | -- |
| ![Start screen](https://user-images.githubusercontent.com/379991/224502477-c429cf45-163b-4537-944a-cf98cfd3a7af.png) | ![Formula screen](https://user-images.githubusercontent.com/379991/224502504-6bb7799a-8e15-4d72-abfd-6d117c34ca05.png) | ![Maintenance sheet](https://user-images.githubusercontent.com/379991/224502526-3ae732a1-b5b5-42b5-ba80-4eeae0bfd4be.png) |
**Settings**
| General | Maintenance | Homebrew (formerly Brew) |
| -- | -- | -- |
| …
> ~ Copy changes to improve consistency/clarity & reduce redundant wording

- Cork/zh-Hans.lproj/Localizable.strings
> + Simplified Chinese localization for Tags

- Cork.xcodeproj/project.pbxproj
- Cork/zh-Hant.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.stringsdict
+ Traditional Chinese localization
> zh-Hant localization

- Cork/en.lproj/Localizable.strings
- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.strings
- Add Simplified Chineses localization for Bug Reporting
- Update Copyright information: `2022` -> `2023`
> + Simplified Chinese localization for Bug Reporting

- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.strings
- Add Simplified Chinese localization for `add-package.network-error` & `add-package.network-error.description`
- Add Traditional Chinese localization for `add-package.network-error` & `add-package.network-error.description`
@sh95014 Hi，你可以帮忙看看繁体的翻译是否合适吗 😄
> + Chinese localization for error messages

- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hans.lproj/Localizable.stringsdict
- Refine Simplified Chinese plurals
- Refine other Simplified Chinese translations
> ~ Simplified Chinese localization

- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.strings
- Add Simplified Chinese localization for Package Repairing
- Readies localizable strings for Traditional Chinese
> + Chinese localization for Package Repairing

- Cork/en.lproj/Localizable.strings
- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.strings
- Update Simplified Chinese localization
- Ready Traditional Chinese localizable strings. 麻烦@sh95014 看一下😄 
- `Chinese` -> `Simplified Chinese` in English strings
> + Chinese localization

- Cork/zh-Hant.lproj/Localizable.strings
- just capitalize brew jargon everywhere for consistency
- also tone down the hatred of Swift JSON parsing
> Update zh-Hant localization

- Cork/zh-Hans.lproj/Localizable.strings
- Add Simplified Chinese localization for menubar.
> + Simplified Chinese localization

- README.md
**Tak** to me on Discord -> **Talk** to me on Discord
> ^ README Typo

- Cork/Views/About/About View.swift
- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.strings
- Add new translations for Simplified Chinese
- Minor tweaks on the pronoun of Simplified Chinese (unified with Apple's localization)
- Add locales for Traditional Chinese
- Changed Jerry's Mastodon link to directly visit the original site
> Update Chinese localization

- Cork/de.lproj/Localizable.strings
- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.strings
- Update Simplified Chinese localization
- Update Traditional Chinese locales
- Update German locales
> Localization Updates

- Cork/de.lproj/Localizable.strings
- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.strings
- Add Traditional Chinese localization for translator `about.translator.3.purpose" = "為 Cork 提供德語翻譯";`
- Add Simplified Chinese localization for translator `about.translator.3.purpose" = "为 Cork 提供了德语翻译";`
- Add new German locales
@sh95014 Could you check the TC translation if you have time 😄
@hecaex New German locales are ready 🚀
> Update Simplified & Traditional Chinese localization

- Cork/de.lproj/Localizable.strings
- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.strings
Based on pull request [Jerry23011:german-translator-localization](https://github.com/buresdv/Cork/pull/119) I translated the translator string into german.
> German translator localization

- Cork/de.lproj/Localizable.strings
- Cork/de.lproj/Localizable.stringsdict
- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hans.lproj/Localizable.stringsdict
- Cork/zh-Hant.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.stringsdict
- Add Simplified Chinese localization for Notifications
- Add Traditional Chinese Localizable strings for Notifications
- Add German Localizable strings for Notifications
- Minor tweak for `untagging` in Simplified Chinese translation
> Update Simplified Chinese localization and Traditional Chinese & German localizable strings

- Cork/zh-Hans.lproj/Localizable.strings
Sorry about missing these two, got a quick fix for them
> Hotfix: Missing Simplified Chinese localization

- Cork/de.lproj/Localizable.strings
Hi,
I took the time to update the german language.
> ~ german translations

- Cork/de.lproj/Localizable.strings
Hi there,
an update for german is ready.
> update german language

- Cork/de.lproj/Localizable.strings
- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.strings
- Add Simplified Chinese localization translations
- Add Traditional Chinese localizable strings
- Add German localizable strings
> Update Localization for update-process-rephrasing branch

- Cork/de.lproj/Localizable.strings
- Cork/de.lproj/Localizable.stringsdict
- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hans.lproj/Localizable.stringsdict
- Cork/zh-Hant.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.stringsdict
- Add Traditional Chinese & Simplified Chinese & German strings
- Add Simplified Chinese translations for `alert.generic.couldnt-parse-json` and `add-package.top-packages.list-item`
> Update Localization for top package count and alert in deciphering brew responses

- Cork.xcodeproj/project.pbxproj
- Cork/Views/About/About View.swift
- Cork/de.lproj/Localizable.strings
- Cork/en.lproj/Localizable.strings
- Cork/fr.lproj/Localizable.strings
- Cork/fr.lproj/Localizable.stringsdict
- Cork/zh-Hans.lproj/Localizable.strings
- Cork/zh-Hant.lproj/Localizable.strings
Hello, here is my pull request for the French translation.
> ~ French translation

- Cork/zh-Hans.lproj/Localizable.strings
- Updated some strings to make the translation more consistent
- Fixed the translation of `about.translator.4.purpose`
> Update Simplified Chinese localization

- Cork/Localizable.xcstrings
I have corrected the plural in French.
> ~ french Localizable

- Cork.xcodeproj/project.pbxproj
- Cork/Logic/Shell/Shell Interface.swift
- Cork/askpass.sh
I've created a small script that uses osascript to request the password, and when a brew command requires sudo, the script is invoked to provide it.
> + Request the sudo password

- Cork/Localizable.xcstrings
- `？` -> `?`
PS I think Xcode automatically formatted some of the French strings.
> Fix SC question mark icon misplacement in cask view

- Cork/Localizable.xcstrings
+ add missing german translations
~ rephrase few messages for improved language flow
> Add missing Translations (German)

- Cork/Localizable.xcstrings
- Minor improvement to notification localization
> ~ SC localization

- Cork/Localizable.xcstrings
https://github.com/buresdv/Cork/issues/206
> Update traditional Chinese localization

- Cork/Localizable.xcstrings
> ^ SC localization

- Cork/Localizable.xcstrings
I also removed the unused `brewfile.export.default-export-name` entry which is superseded by `brewfile.export.default-export-name-%@`.
> + Russian localization for new strings

- Cork.xcodeproj/project.pbxproj
- Cork/Localizable.xcstrings
- Cork/Views/About/About View.swift
This Pull Request provides Ukrainian translation of app.
> Added Ukrainian translation

- Cork/Localizable.xcstrings
- Cork/Views/About/About View.swift
- Add new SC translations
- Adjusted my translator info since all translators use GitHub
> + SC Localization

- Cork/Localizable.xcstrings
I updated some German localization like singular/plural mistakes and small translation errors
> ~ German localization

- README.md
> ~ typo correction

- Cork/Localizable.xcstrings
- Add new translations for Homebrew localization customization
> Update SC Localization

- Cork/Localizable.xcstrings
Added missing German localizations, mostly related to custom Homebrew paths.
> Add missing German translations

- Cork/Localizable.xcstrings
- README.md
1. The "`Buy Cork` for 25€" UI is problematic for translations. In Chinese it would be less awkward to phrase it as "以 25 歐元 `購買 Cork`" but that requires a code change. I suggest you move the "for 25€" into the button.
2. While running the app to test the translations, it seems that a user will now be blocked from using the app (beyond the 7-day trial) unless they purchase. You 100% deserve to be paid for your work, but I also don't feel the need to contribute my efforts to a paid app going forward. Best of luck!
3. Same issue with `README.md` as the other PR.
> update zh_Hant for licensing

- Cork/Localizable.xcstrings
Hi it's me again. I have a little update for the German language inside Cork.
> ~ German language

- Cork/Localizable.xcstrings
Your file has been uploaded, please confirm.
> Uploading Korean files 

- Cork/Localizable.xcstrings
> korean translate 99%

- Cork/Localizable.xcstrings
Hi there 👋,
a few new german string are available and ready to be merged once more.
> + german strings

- Cork/Localizable.xcstrings
Hey,
I've updated the german strings for the new release!
> ~german strings

- README.md
Hey @buresdv 👋 
We talked briefly on Bsky. Just came here to check out the repo and found a tiiiiiiiiny little typo in the doc. Thought I'd fix it. 😅
> Fixing typo in the README

- Cork.xcodeproj/project.pbxproj
- Cork/Localizable.xcstrings
Completed es-LA localization. It could also be used as the es locale.
> es-LA localization

- .github/workflows/swift.yml
Test results: https://github.com/cclauss/Cork/actions
* `swift build` and `swift test` would require a `Package.swift` file.
> Add GitHub Action to run swiftlint, swift build, and swift test

- .package.resolved
- Cork/Localizable.xcstrings
- Tuist/Package.resolved
FIx some typos and add some new items.
> Update some translation of Chinese(Simplified)

- Cork/Localizable.xcstrings
Added English (United Kingdom) translation.
> + English (United Kingdom) Translation

- Cork/Logic/App Intents/Shortcuts Provider/Cork Shortcuts.swift
> ^Update Cork Shortcuts.swift

- Cork/Localizable.xcstrings
+ Updated English (United Kingdom) Translations
> + Updated English (United Kingdom) Translations

- Cork/Localizable.xcstrings
> +SC Localization

- Cork/Localizable.xcstrings
I localised the entire app in Italian and will keep maintaining it. Thank you for this utility.
> Add Italian localisation

- Cork/Localizable.xcstrings
- Fix errors in translations like 'complete' in the context of display format
- Fix inconsistency in translations across the project
- Polish some existing translations to feel more natural and authentic in Chinese
> fix: Update localization strings for zh-Hans

- Cork/Localizable.xcstrings
> Update Italian locale
