Cork/Views/Start Page/Start Page.swift
I opened Cork and found that it was stuck in the 'checking for package updates' state with a loading indicator. The `StartPage` view would always show the loading state as long as `upgradeablePackages.isEmpty` was `true`, but in my case `upgradeablePackages` was always empty as there were no packages to update.
=> Fix start page appearing to be stuck checking for package updates

Cork/Logic/Shell/Shell Interface.swift, Cork/Models/Terminal Output.swift
This PR:
* Adds a function to produce an async stream of terminal output incrementally as it's received (standard output & standard error)
* Re-works the existing `shell` function to give standard output & standard error all at once via the new stream function – matching the existing function's behaviour
Hoping this fulfils the requirements listed in the README! 😅 
I've lightly tested and found nothing obviously broken by changing the underlying shell interface implementation. Adding print statements showed each line of standard output being logged.
Example usage:
```swift
for await output in shell("/opt/homebrew/bin/brew", ["install", package.name])
{
// `switch` on `output` or do something else
print(output)
}
```
=> + Real-time stream from shell interface

Cork/App State.swift, Cork/ContentView.swift, Cork/CorkApp.swift, Cork/Logic/Load up Tapped Taps.swift, Cork/Logic/Shell/Brew Interface.swift, Cork/Models/Brew Data Storage.swift, Cork/Views/Sidebar/Sidebar View.swift, Cork/Views/Start Page/Start Page.swift, Cork/Views/Taps/Add Tap.swift
Change terminology to use 'tap' as a verb rather than both a verb and noun, to avoid the confusing phrase 'tap a tap'. [Homebrew's own documentation](https://docs.brew.sh/Taps) refers to tapping repositories so I think this is a safe and technically accurate change, and I'd argue it's more understandable even from an outside perspective.
=> ~ Change terminology from 'tap a tap' to 'add a tap'

Cork/Views/Installation/Install Package.swift, Cork/Views/Maintenance/Sub-Views/Ready View.swift, Cork/Views/Taps/Add Tap.swift
Disable confirmation buttons (add tap, install package, start maintenance, search) when no action is possible – for example, text field is empty, no package has been selected, or no maintenance options have been selected.
=> + Disable confirmation buttons when no action is possible

Cork/Views/Packages/Package Details/Package Details.swift
Only show an 'expand' button if the package caveats text hits the line limit.
I can't take credit for the solution though – [courtesy of StackOverflow](https://stackoverflow.com/a/75352076/447697) 😅  First time using `ViewThatFits`, pretty happy with how this works, as there was at least one hackier approach in the running.
Tested with the packages `six` (formatted caveats on 2 lines) and `nvm` (formatted caveats on 12 lines).
=> ~ Only allow package caveats to be expanded if text is more than line limit

Cork/Views/Packages/Package Details/Package Details.swift
Fixes a regression from #36 in which package caveats text no longer rendered Markdown correctly.
Re-instates a call to the `LocalizedStringKey` initialiser (`.init(..)`) passing in the caveats text, in order to render Markdown. This was accidentally removed in my PR!
=> ~ Fix caveats not rendering markdown (regression from #36)

Cork/CorkApp.swift, Cork/Views/Maintenance/Sub-Views/Ready View.swift, Cork/Views/Start Page/Start Page.swift
Append an ellipsis to menu items and buttons which require confirmation or show further info before completing an action, as per Apple's Human Interface Guidelines (https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/menus/#labels) (this is also more consistent with other macOS apps)
=> ~ Use ellipsis to indicate actions that require confirmation/show further info

Cork/Styles/DisclosureGroup - No Padding.swift, Cork/Views/About/About View.swift, Cork/Views/Loading View.swift, Cork/Views/Packages/Package Details/Package Details.swift, Cork/Views/Packages/Package List Item.swift, Cork/Views/Reusables/Complex with Icon.swift, Cork/Views/Reusables/GroupBox Headline Group.swift
Use the `secondary` color instead of `gray` across the app, as `secondary` seems to adapt to the display context. For example, it adapts to a lighter variant when used in a selected sidebar item view, making the version number easier to read for a selected package.
| Before | After |
| -- | -- |
| ![Before](https://user-images.githubusercontent.com/379991/224560060-7eb91f04-4f15-4ff9-839b-b45600cf7a51.png) | ![After](https://user-images.githubusercontent.com/379991/224560067-dad3a744-4bc8-4850-b54e-510317e64b2e.png) |
=> ~ Use `secondary` instead of `gray` foreground color

Cork/Views/About/About View.swift
Replaces the deprecated uses of the `animation` modifier without a value with `.transaction { $0.animation = nil }`
=> ~ Use `transaction` to remove animation instead of deprecated `.animation(.none)`

Cork/Logic/Shell/Shell Interface.swift
Add support for providing environment variables to `shell`, defaulted to `nil` (none).
=> + Add support for providing environment variables to `shell`

Cork/Views/Reusables/GroupBox Headline Group.swift
Fixes compile error due to wrong type of `image` in  `GroupBoxHeadlineGroupWithArbitraryContent`
=> Fix type error in GroupBoxHeadlineGroupWithArbitraryContent

Cork/Views/Settings/Panes/General Pane.swift, Cork/zh-Hans.lproj/Localizable.strings
- Added Simplified Chinese translations for the translator section :)
- Fixed `Package caveats:` & `Package details:` not localizable
P.S. For anyone who might contribute to the Chinese translation of Cork: I used `软件包` instead of `包` for "package" because that's what they use on homebrew's [official website](https://brew.sh/index_zh-cn). Personally, I prefer the second one, which is more concise, but still, let's respect the official translation.
=> + Chinese translations for Translator section

Cork/Views/Taps/Tap Details/Tap Details.swift
...so that the "Number of Packages" says "6,605" instead of "6605".
=> format package count (mainly for thousands separator)

Cork/CorkApp.swift, Cork/Views/Packages/Package List Item.swift
I'm running macOS 13.5.1 with Xcode 14.3.1 and I had some compilation errors for missing members and arguments.
I've updated the code accordingly.
Since Swift 5.8 attributes can be checked with `hasAttribute` I used this compile conditional
to check for the [Animation.bouncy](https://developer.apple.com/documentation/swiftui/animation/bouncy?changes=latest_minor) attribute, thats available starting from Xcode 15.
Also `NSApp.activate` requires a parameter `ignoringOtherApps` on Xcode 14.
The parameter could be available in Xcode 15 too, so reducing the function `func switchCorkToForeground()` to
`func switchCorkToForeground()
{
NSApp.activate(ignoringOtherApps: true)
}
`
might be sufficient.
However I cannot find any documentation about `.activate()` on versions prior to Xcode 15 for …
=> Fix compilation errors on Xcode 14

Cork/de.lproj/Localizable.strings, Cork/zh-Hans.lproj/Localizable.strings, Cork/zh-Hant.lproj/Localizable.strings
- Add localizable strings for German & Chinese
- Update Simplified Chinese localization for `"alert.notification-could-not-remove-tap-due-to-packages-from-it-still-being-installed.message-%@"`
=> Update localization for untapping fix

Cork.xcodeproj/project.pbxproj, Cork/App State.swift, Cork/AppDelegate.swift, Cork/ContentView.swift, Cork/Logic/Discoverability/Load up Top Packages.swift, Cork/Logic/File System/File Browser/Get Contents of Folder.swift, Cork/Logic/Tagging/File Handling/Save Tagged IDs to Disk.swift, Cork/Views/Installation/Components/Searching View.swift, Cork/Views/Installation/Reusables/Search Result Row.swift, Cork/Views/Packages/Package Details/Package Details.swift, Cork/Views/Settings/Panes/Notifications Pane.swift, Cork/Views/Taps/Tap Details/Tap Details.swift
Fixes the warnings emitted by setting `SWIFT_STRICT_CONCURRENCY` to `targeted`. I'll add some comments inline to discuss individual changes. 
There is more work to do to get this to `complete` but I think this resolves all the `targeted` warnings to start with.
=> Handle targeted concurrency warnings

Cork.xcodeproj/project.pbxproj, Cork/Models/Searching/Package Search Token.swift, Cork/Views/Sidebar/Components/Casks Section.swift, Cork/Views/Sidebar/Components/Formulae Section.swift, Cork/Views/Sidebar/Components/Sidebar Package Row.swift, Cork/Views/Sidebar/Components/Taps Section.swift, Cork/Views/Sidebar/Sidebar View.swift
Main changes:
* Merge `TokenSearchType` and `PackageSearchToken` into an enum with properties for name and icon, which slightly simplifies some of the array logic in the sidebar view
* Extract a reusable view for sidebar package row views – this is now used in both the formulae and casks sections
I think there's room for further refactoring and simplification, but this felt like an incremental step in the right direction.
=> ~ Simplify sidebar search tokens and section views

Cork/ContentView.swift, Cork/Views/Sidebar/Components/Sidebar Package Row.swift, Cork/Views/Sidebar/Components/Taps Section.swift, Cork/Views/Sidebar/Sidebar View.swift
What's Changed:
- Replace `NavigationView` with `NavigationSplitView`.
- Replace deprecated `NavigationLink` calls.
Additional Context:
- NavigationLink destination views now have explicit identities assigned to them. Without it, split view fails to recognize that a new sidebar row has been selected.
- Sidebar list now gets a reference to `appState.navigationSelection`. This is needed to keep existing Home button behaviour (without it, it doesn't work at all).
Notes:
I didn't add anything to toggle the sidebar button visibility for two reasons:
- Requires macOS 14.0.
- When I first ran this app, the sidebar view was hidden for some reason (and there was no sidebar icon), and I got *very* confused.
=> Migrate to new navigation APIs

Cork/Views/Start Page/Sub-Views/Outdated Packages/Outdated Package List Box.swift
I was trying out Cork for the first time when I noticed that the "deselect all" and "select all" buttons in the "Outdated packages" list weren't working. The fix was straightforward.
=> ^ (de)select all doesn't work in outdated list

Cork/ContentView.swift
Seems like in one of Brew updates they changed the output format of `brew analytics`. It now prints:
```
InfluxDB analytics are enabled.
Google Analytics were destroyed.
```
However, Cork was looking for a `"Analytics are enabled"` substring (notice the capital A).  
This caused Cork to incorrectly assume that analytics are disabled, despite being the opposite.
I fixed it by using a case-insensitive version of `contains` to keep compatibility with old Brew versions which may have the old `brew analytics` output format.
=> ^ Detection of analytics being enabled

Cork/Views/Start Page/Sub-Views/Outdated Packages/Outdated Package List Box.swift
I'm trying out Cork, and I noticed when toogle outdated list package it will select or de-select wall list.
=> ^ Single outdated packages toggle doesn't work in outdated list

Cork/Views/Shared/PillText.swift
According to [Apple Developer Document](https://developer.apple.com/documentation/swiftui/capsule#overview):
> A capsule shape is equivalent to a rounded rectangle where the corner radius is chosen as half the length of the rectangle’s smallest edge.
- `Capsule`: <https://developer.apple.com/documentation/swiftui/capsule>
- `RoundedRectangle`: <https://developer.apple.com/documentation/swiftui/roundedrectangle>
| Before | After |
| ------ | ----- |
| ![截屏2024-01-11 20.09.54](https://github.com/buresdv/Cork/assets/29367025/ea2f962e-73d8-4538-bfd4-fb871828ca26) | ![截屏2024-01-11 20.08.22](https://github.com/buresdv/Cork/assets/29367025/b876e9a1-9db7-4b12-b1ae-aceac3d947f1) |
| ![截屏2024-01-11 20.10.00](https://github.com/buresdv/Cork/assets/29367025/04a63844-c960-416e-9b04-c1244727c0da) | …
=> Fix `OutlinedPillText` radius to prevent text overflow

Cork/Views/Maintenance/Sub-Views/Maintenance Finished View.swift
=> Fixed alert width size

Cork/Localizable.xcstrings, Cork/Views/Packages/Package Details/Sub-Views/Package Modification Buttons.swift
While using the application, I accidentally uninstalled a package. I would expect a confirmation before running the destructive action.
This PR adds a confirmation dialog when uninstalling/purging a package, avoiding accidental clicks.
=> Add confirmation dialog when uninstalling/purging a package

Cork/Logic/Brewfile/Export Brewfile.swift
When trying to export a Homebrew backup, I got the following error message:
```
Couldn't write Homebrew backup
Try again, or restart Cork
```
Somehow, an existing `Brewfile` was already present in the temporary directory, leading Brew to throw an error.
This PR adds a flag to force the dump to overwrite an existing Brewfile:
`brew bundle -f dump`.
=> Force dump to overwrite an existing Brewfile

Cork/Localizable.xcstrings, Cork/Logic/File System/File Browser/Get Contents of Folder.swift, Cork/Models/JSON/Tap Codable Model.swift, Cork/Views/Packages/Package Details/Package Details.swift, Cork/Views/Start Page/Sub-Views/Outdated Packages/Outdated Package List Box.swift, Cork/Views/Taps/Tap Details/Sub-Views/Tap Info.swift, Cork/Views/Taps/Tap Details/Tap Details.swift, crowdin.yml
When viewing the list of outdated packages, it can be useful to quickly know what a packge does or other info about it. This adds an info button beside each package name that opens a popover rendering the existing Package Details View.
=> Add package details popover to the outdated packages list

README.md
Very simple and works the same: https://mise.jdx.dev/getting-started.html#homebrew
It supports by default only zsh and fish, but bash isn't default since Catolina, so it shouldn't be a problem in most cases.
=> Simplify `Mise` installation in README

Cork/Logic/Packages/Load Up Package Info.swift, Cork/Models/Packages/Brew Package Details.swift
Previously, an error would occur during decoding when the `formulae.bottle` key was empty, thereby preventing the package details view from being shown.
The struct now represents this possibility as an optional, allowing this key to decode correctly when empty (in which case it will be ignored).
For example, `arena` from [this tap](https://github.com/finestructure/homebrew-tap) returns an otherwise well-formed JSON response with an empty `formulae.bottle` value.
=> ^ Optional Formulae.Bottle.Stable in JSON decoding

Cork/Localizable.xcstrings
When there is exactly one unloaded cask, it now displays as a number ("1") instead of as a word ("one") to match how unloaded formulae are displayed in English.
Before:
After:
=> ^ Unloaded package number formatting (English)

Cork/Localizable.xcstrings, Cork/Logic/Package Loading/Load Up Installed Packages.swift, Cork/Logic/Search for Package by ID.swift, Cork/Models/Package Installation/Installation Progress Tracker.swift, Cork/Models/Package Uninstallation/Uninstallation Confirmation Tracker.swift, Cork/Models/Packages/Brew Package.swift, Cork/Views/Installation/Reusables/Search Result Row.swift, Cork/Views/Installation/Sub-Views/Initial/Top Packages Section.swift, Cork/Views/Installation/Sub-Views/Searching.swift, Cork/Views/Reusables/Buttons/Preview Package.swift, Cork/Views/Updating/Incremental Updating/Update Some Packages View.swift
Previously, the size of each installed package was eagerly calculated at launch. However, this is expensive, and can be unnecessary in many cases. (This property's main use is for sorting the sidebar list by package size, so if another sort mode is selected, the compute is wasted.)
Package sizes are now calculated lazily. To support this, package models are initialized with their URL instead of the size value proper. The size is cached to prevent it from being re-computed on every access.
Profiling this change, I observed the hang at startup to be 55% shorter, down from 2.8s to 1.2s.
(Conducted on M1 Max via Xcode/Instruments, sorting by Name, ~200 Brew packages installed.)
The main downside of this approach is that there is now a noticeable hang when first changing to Size sort mode; …
=> ~ Lazily Get Package Size

Cork/Localizable.xcstrings, Cork/Logic/Shell/Shell Interface.swift, Cork/Views/Settings/Panes/Installation Pane.swift
Partial fix for #305.
This PR adds an option that sets the `HOMEBREW_ACCEPT_EULA` environment variable.
If enabled, installation proceeds without requesting input on packages that require accepting a EULA (such as `microsoft/mssql-release/msodbcsql18`).
This PR does not change the way that inter-process IO is managed—
Thus, if the user attempts to install such a package with the option disabled, it will still hang indefinitely.
=> + Option to automatically accept package EULAs

Cork/Logic/Shell/Shell Interface.swift, Cork/Models/Package Installation/Installation Progress Tracker.swift, Cork/Views/Installation/Install Package.swift
Previously, cancelling an installation would not terminate the child process.
So, if Brew were to hang (eg due to waiting for input), it would remain as a zombie until manually killed via Activity Monitor or the like.
Due to Brew's locking mechanisms, this also means that no other process would be able to access the package in question.
To prevent this, a `shell` overload returning the spawned process has now been added, allowing InstallationProgressTracker to terminate it upon cancellation.
=> ^ Zombie process when installation cancelled

Cork/Views/Start Page/Sub-Views/Outdated Packages/Outdated Package List Box.swift
Fixes the "Update x packages" button which is used when not all packages are selected for updating.
Previously this button would not show the expected sheet.
This is not a total solution—the partial update view is still not at parity with the full update view.
=> Quick-fix partial update sheet

Cork/Localizable.xcstrings
Update the Simplified Chinese (`zh-Hans`) translations to improve clarity and consistency. The changes primarily involve rephrasing strings to make them more concise and align better with the intended meaning.
=> Update zh-Hans translations

README.md
The README now provides more detailed instructions on how to use mise with tuist for compiling Cork.
Instead of using `mise use`, which modifies the local environment, the instructions now recommend using `mise exec` to run tuist commands with a specific version without permanently changing settings.
This approach gives users more control over their environment and explains the trust prompt that mise displays when encountering a new project configuration.
=> 📝 ^ Update README with clearer mise usage instructions for build

Cork/Views/Installation/Sub-Views/Misc Views/Live Code Output.swift, Cork/Views/Maintenance/Sub-Views/Maintenance Finished View.swift, Cork/Views/Updating/Complete Updating/Sub-Views/States/Checking for Updates.swift, Cork/Views/Updating/Complete Updating/Sub-Views/States/Updating Package Tracker.swift, Cork/Views/Updating/Complete Updating/Sub-Views/States/Updating Packages.swift, Cork/Views/Updating/Complete Updating/Update Packages View.swift
=> +  Improve popups layout performance, adaptive width and line breaks
